### ISSUE TITLE
Can't preview on any android emulator - x86 support

### ISSUE THREAD

**Issue by cliqer** [fuse-open/fuse-studio#18]
Tried with genymotion and android studio emulators on mac and the build always fails:
`INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113 `

Tried also with armeabi-v7a and apk does not install because the emulator is very unstable and keeps crashing.

Is there any way or any cli commands to force the x86 compiler?

**Comment by ichan-mb** [comment]
https://github.com/fuse-open/uno/pull/398
