### ISSUE TITLE
Fuse Studio 1.12

### ISSUE THREAD

**Issue by Jean-Regis** [fuse-open/fuse-studio#43]
I know that you do not want to waste resources keeping it up to date, but would it be possible (if feasible) to get a guide on how to update the uno version of studio ? 

Or does that impact Studio in too many different ways ?

Thanks in advance.

_Loves Fuse 1.12 but misses the quick change previews of studio <3_

**Comment by egislook** [comment]
I just started using Fuse and I installed 1.9.0 studio and used [this answer](https://forums.fusetools.com/t/oct-2018-fresh-install-of-android-with-fuse-1-9-0-on-windows-10-64bit/7469) to make it running. Tried newer versions but no luck. Live previous works tho im missing the topBar

**Comment by mortend** [comment]
There's a new 2.0 Beta version of Fuse Studio available at https://github.com/fuse-x/studio/releases

Latest Uno and Fuselibs included.
